### ISSUE TITLE
[BUG] PHP 7 method signature compatibility

### ISSUE THREAD

**Issue by floriancourgey** [lemonwaysas/prestashop-lemonway-plugin#6]
Hi,

With PS 1.7, PHP 7 and lemonway 1.3 I have the following error:

ContextErrorException in AdminMoneyOutController.php line 30:
Warning: Declaration of AdminMoneyOutController::l($string) should be compatible with AdminControllerCore::l($string, $class = NULL, $addslashes = false, $htmlentities = true)

when clicking on any menu item (e.g. Lemonway > Virements bancaires)

I'll try to do a PR if I got the time

Thanks
Florian

**Comment by pham-dat** [comment]
Thank you, I merged your PR.
