### ISSUE TITLE
Undefined variable: adminSplitPaymentTabUrl

### ISSUE THREAD

**Issue by floriancourgey** [lemonwaysas/prestashop-lemonway-plugin#8]
URL /admin-dev/index.php?controller=AdminModules&configure=lemonway

gives the following error in a red popup:

Notice à la ligne 582 du fichier /var/www/vhosts/vps493658.ovh.net/shop.bonnemine.co/modules/lemonway/lemonway.php
[8] Undefined variable: adminSplitPaymentTabUrl

**Comment by pham-dat** [comment]
Fixed.
Thanks for your contribution.
